name: Build iOS .ipa

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      APP_IDENTIFIER: com.ajamba
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_DEVELOPER_EMAIL: ${{ secrets.APPLE_DEVELOPER_EMAIL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS deps
        run: npm install

      - name: Setup Ruby & CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'
      - run: |
          cd ios
          pod install

      - name: Decode cert & profile
        run: |
          mkdir ios/certs
          echo "${{ secrets.APPLE_CERTIFICATE_P12 }}" | base64 --decode > ios/certs/dist.p12
          echo "${{ secrets.APPLE_PROVISIONING_PROFILE }}" | base64 --decode > ios/certs/profile.mobileprovision

      - name: Install cert in keychain
        run: |
          security create-keychain -p "" build.keychain
          security import ios/certs/dist.p12 \
            -k ~/Library/Keychains/build.keychain \
            -P "${{ secrets.APPLE_CERTIFICATE_PASSWORD }}" \
            -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain

      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp ios/certs/profile.mobileprovision \
             ~/Library/MobileDevice/Provisioning\ Profiles/${{ env.APP_IDENTIFIER }}.mobileprovision

      - name: Archive with Xcode
        run: |
          xcodebuild archive \
            -workspace ios/ajamba.xcworkspace \
            -scheme ajamba \
            -configuration Release \
            -archivePath build/ajamba.xcarchive \
            DEVELOPMENT_TEAM=${{ env.APPLE_TEAM_ID }} \
            PROVISIONING_PROFILE_SPECIFIER=${{ env.APP_IDENTIFIER }}

      - name: Export .ipa
        run: |
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
           "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>        <string>ad-hoc</string>
            <key>teamID</key>        <string>${{ env.APPLE_TEAM_ID }}</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${{ env.APP_IDENTIFIER }}</key>
              <string>${{ env.APP_IDENTIFIER }}</string>
            </dict>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath build/ajamba.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa

      - name: Publicar artefacto .ipa
        uses: actions/upload-artifact@v3
        with:
          name: ajamba-ios-ipa
          path: build/ipa/*.ipa
