name: Build iOS .ipa

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS deps
        run: npm install

      - name: Setup Ruby & CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.x'
      - run: |
          cd ios
          pod install

      - name: Archive with Xcode
        run: |
          xcodebuild archive \
            -workspace ios/ajamba.xcworkspace \
            -scheme ajamba \
            -configuration Release \
            -archivePath build/ajamba.xcarchive

      - name: Export .ipa
        run: |
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
           "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>        <string>development</string>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath build/ajamba.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa

      - name: Upload .ipa as artifact
        uses: actions/upload-artifact@latest
        with:
          name: ajamba-ios-ipa
          path: build/ipa/*.ipa
